apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - name: portgress
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  replicas: 1
  serviceName: postgresql-service
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: openremote/postgresql:latest
          envFrom:
            - secretRef:
                name: postgresql-environment
          ports:
            - containerPort: 5432

          # Kiểm tra container có hoạt động bình thường không (liveness)
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U postgres -d openremote"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Kiểm tra container đã sẵn sàng phục vụ truy vấn chưa (readiness)
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U postgres -d openremote"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
